### ISSUE TITLE
MD-004: Write Mock tests

### ISSUE THREAD

**Issue by YaroslavSE** [YaroslavSE/Mail#5]

**Comment by Denys200529** [comment]
I implemented mock tests for the classes Mail, PostalOffice, and PostalService. I created three separate test classes, each focusing on mocking the behavior of dependencies and testing the interactions between components.

MailTest:

- Mocked external dependencies related to mail processing and tested methods of the Mail class.
- Ensured that the class correctly handles mail attributes and interacts with other components as expected.

PostalOfficeTest:

- Mocked interactions between the PostalOffice class and other entities (e.g., Mail, User).
- Verified that the class correctly processes mail, handles users, and interacts with other services.

PostalServiceTest:

- Mocked external services and systems that the PostalService class depends on.
- Tested the system-wide behavior of PostalService, ensuring that it can coordinate multiple PostalOffice instances and properly handle mail logistics.

These mock tests ensure that each class behaves correctly in isolation, and they help verify the interactions between components in the system.
