### ISSUE TITLE
MD-007: Add builder for classes

### ISSUE THREAD

**Issue by YaroslavSE** [YaroslavSE/Mail#8]

**Comment by Denys200529** [comment]
For this task, I implemented a Builder pattern for the Mail class to simplify the creation and customization of mail objects. The MailBuilder class provides a fluent interface, allowing the construction of a Mail object step by step.

Key features of the MailBuilder:

- Fluent Interface: Allows chaining of setter methods to set values for itemId, sender, receiver, content, weight, sentDate, deliveredDate, and status.

- Validation: Ensures required fields, such as itemId and receiver, are properly set before building the Mail object.

- Error Handling: Throws an exception if essential fields are missing or incorrectly set.

This builder design improves the readability and maintainability of the code by making the creation of Mail objects more flexible and error-resistant.
